language: python

sudo: false

branches:
  except:
    - gh-pages

python:
  - 3.6

cache: pip

virtualenv:
  system_site_packages: false

install:
  - pip install pipenv
  - pipenv install --system

script:
  - nikola build --no-continue --strict

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
  on:
    branch: master
